//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinalEval
{
    using System;
    using System.Collections.Generic;
    
    public partial class freelance
    {
        public int IDFREELANCE { get; set; }
        public string NOMFL { get; set; }
        public string PRENOMFL { get; set; }
        public string EMAILFL { get; set; }
        public Nullable<int> TELEPHONE { get; set; }
    }
}
