//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinalEval
{
    using System;
    using System.Collections.Generic;
    
    public partial class variable
    {
        public int IDVARIABLE { get; set; }
        public int IDCOLLABORATEURTITULAIRE { get; set; }
        public Nullable<int> TAUX { get; set; }
        public Nullable<int> PERIODE { get; set; }
    
        public virtual collaborateurtitulaire collaborateurtitulaire { get; set; }
    }
}
